channels:
- conda-forge
dependencies:
- pip:
  - flit
  - acoustics~=0.2.6
  - mosqito~=1.0.8
  - scikit-maad~=1.3.6.1
#  - beni~=0.4.4
- python>=3.7.12,<3.8
- pip
- pandas~=1.3.5
- openpyxl~=3.0.10
- seaborn~=0.12.1
- pyyaml~=6.0
- pyjanitor~=0.23.1
- jupyter~=1.0.0
- black
- sphinx~=5.3.0
- sphinx-rtd-theme~=1.1.1
- pytest~=7.1.3
name: soundscapy

