# Settings file for batch acoustic analysis.
# Split up according to which library performs which analysis.


# Python Acoustics
# Supported metrics: LAeq, LZeq, LCeq, SEL
# Supported stats: avg/mean, max, min, kurt, skew, any integer from 1-99
PythonAcoustics:
    LAeq:
        run: true
        main: 'avg'
        statistics: [5, 10, 50, 90, 95, 'min', 'max', 'kurt', 'skew']
        channel: ["Left", "Right"]
        label: 'LAeq'
        func_args:
            time: 0.125
            method: "average"

    LZeq:
        run: true
        main: 'avg'
        statistics: [5, 10, 50, 90, 95, 'min', 'max', 'kurt', 'skew']
        channel: ["Left", "Right"]
        label: 'LZeq'
        func_args:
            time: 0.125
            method: "average"

    LCeq:
        run: true
        main: 'avg'
        statistics: [5, 10, 50, 90, 95, 'min', 'max', 'kurt', 'skew']
        channel: ["Left", "Right"]
        label: 'LCeq'
        func_args:
            time: 0.125
            method: "average"

    SEL:
        run: true
        main: []
        statistics: []
        channel: ["Left", "Right"]
        label: 'SEL'

# MoSQITO 
# supported metrics: loudness_zwtv, sharpness_din_from_loudness, roughness_dw
# supported stats: avg/mean, max, min, kurt, skew, any integer from 1-99
MoSQITO:
    loudness_zwtv:
        run: false
        main: 5
        statistics: [10, 50, 90, 95, 'min', 'max', 'kurt', 'skew', 'avg']
        channel: ["Left", "Right"]
        label: "N"
        func_args:
            field_type: "free"

    sharpness_din_from_loudness:
        run: true
        main: "avg"
        statistics: [5, 10, 50, 90, 95, 'min', 'max', 'kurt', 'skew']
        channel: ["Left", "Right"]
        label: "S"
        func_args:
            weighting: "din"
            skip: 0.5
            field_type: "free"

    sharpness_din_perseg:
        run: false
        main: "avg"
        statistics: [5, 10, 50, 90, 95, 'min', 'max', 'kurt', 'skew']
        channel: ["Left", "Right"]
        label: "S"
        func_args:
            weighting: "aures"
            nperseg: 4096
            field_type: "free"

    # sharpness_din_tv relies on loudness calcs.
    # It's recommended to use sharpness_din_from_loudness instead.
    sharpness_din_tv:
        run: false
        main: "avg"
        statistics: [5, 10, 50, 90, 95, 'min', 'max', 'kurt', 'skew']
        channel: ["Left", "Right"]
        label: "S"
        func_args:
            weighting: "din"
            field_type: "free"
            skip: 0.5

    roughness_dw:
        run: false
        main: "avg"
        statistics: [5, 10, 50, 90, 95, 'min', 'max', 'kurt', 'skew']
        channel: ["Left", "Right"]
        label: "R"

scikit-maad:
maad:
    all_temporal_alpha_indices:
        run: false
        channel: ["Left", "Right"]

    all_spectral_alpha_indices:
        run: false
        channel: ["Left", "Right"]
